package unitedbpapi

// Code generated by "weaver generate". DO NOT EDIT.
import (
	"context"
	"github.com/ServiceWeaver/weaver/runtime/codegen"
	"github.com/yeyee2901/unitedb-api-proto/gen/go/unitedb/v1"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
	"reflect"
	"time"
)

func init() {
	codegen.Register(codegen.Registration{
		Name:     "github.com/yeyee2901/service-weaver/service/unitedbapi/UniteDBService",
		Iface:    reflect.TypeOf((*UniteDBService)(nil)).Elem(),
		New:      func() any { return &grpcUniteDBService{} },
		ConfigFn: func(i any) any { return i.(*grpcUniteDBService).WithConfig.Config() },
		LocalStubFn: func(impl any, tracer trace.Tracer) any {
			return uniteDBService_local_stub{impl: impl.(UniteDBService), tracer: tracer}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any {
			return uniteDBService_client_stub{stub: stub, getBattleItemMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/yeyee2901/service-weaver/service/unitedbapi/UniteDBService", Method: "GetBattleItem"})}
		},
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return uniteDBService_server_stub{impl: impl.(UniteDBService), addLoad: addLoad}
		},
	})
}

// Local stub implementations.

type uniteDBService_local_stub struct {
	impl   UniteDBService
	tracer trace.Tracer
}

func (s uniteDBService_local_stub) GetBattleItem(ctx context.Context, a0 string, a1 string, a2 string) (r0 *unitepb.GetBattleItemResponse, err error) {
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "unitedbpapi.UniteDBService.GetBattleItem", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.GetBattleItem(ctx, a0, a1, a2)
}

// Client stub implementations.

type uniteDBService_client_stub struct {
	stub                 codegen.Stub
	getBattleItemMetrics *codegen.MethodMetrics
}

func (s uniteDBService_client_stub) GetBattleItem(ctx context.Context, a0 string, a1 string, a2 string) (r0 *unitepb.GetBattleItemResponse, err error) {
	// Update metrics.
	start := time.Now()
	s.getBattleItemMetrics.Count.Add(1)

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "unitedbpapi.UniteDBService.GetBattleItem", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
		err = s.stub.WrapError(err)

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
			s.getBattleItemMetrics.ErrorCount.Add(1)
		}
		span.End()

		s.getBattleItemMetrics.Latency.Put(float64(time.Since(start).Microseconds()))
	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	size += (4 + len(a1))
	size += (4 + len(a2))
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	enc.String(a1)
	enc.String(a2)
	var shardKey uint64

	// Call the remote method.
	s.getBattleItemMetrics.BytesRequest.Put(float64(len(enc.Data())))
	var results []byte
	results, err = s.stub.Run(ctx, 0, enc.Data(), shardKey)
	if err != nil {
		return
	}
	s.getBattleItemMetrics.BytesReply.Put(float64(len(results)))

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = serviceweaver_dec_ptr_GetBattleItemResponse_8ca2364b(dec)
	err = dec.Error()
	return
}

// Server stub implementations.

type uniteDBService_server_stub struct {
	impl    UniteDBService
	addLoad func(key uint64, load float64)
}

// GetStubFn implements the stub.Server interface.
func (s uniteDBService_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	case "GetBattleItem":
		return s.getBattleItem
	default:
		return nil
	}
}

func (s uniteDBService_server_stub) getBattleItem(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()
	var a1 string
	a1 = dec.String()
	var a2 string
	a2 = dec.String()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.GetBattleItem(ctx, a0, a1, a2)

	// Encode the results.
	enc := codegen.NewEncoder()
	serviceweaver_enc_ptr_GetBattleItemResponse_8ca2364b(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

// Encoding/decoding implementations.

func serviceweaver_enc_ptr_GetBattleItemResponse_8ca2364b(enc *codegen.Encoder, arg *unitepb.GetBattleItemResponse) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.EncodeProto(arg)
	}
}

func serviceweaver_dec_ptr_GetBattleItemResponse_8ca2364b(dec *codegen.Decoder) *unitepb.GetBattleItemResponse {
	if !dec.Bool() {
		return nil
	}
	var res unitepb.GetBattleItemResponse
	dec.DecodeProto(&res)
	return &res
}
